### ISSUE TITLE
Progress tracking issue for 1.1 beta 3 release

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2713]
## Before the release
- [x] Do a fresh clone of the repository
- [x] Verify that index.php, SSI.php, install.php and upgrade.php have the correct CURRENT_VERSION and CACHE_STALE.
- [x] Write a draft of the release announcement. It should consist of:
   * a general description of the release
   * a *release notes* document including the major changes since the previous version (for development versions like alpha, beta and RC is the previous dev version, for final versions is the previous stable version).
   * a *known issues* document listing the major issues affecting the release (i.e. bugs not critical enough to be blocker, but potentially annoying)

The following command helps writing the list of changes used in the *release notes*:
```
git log --pretty=format:'[*][bugfix] %s ([url=https://github.com/elkarte/Elkarte/commit/%h]ref[/url]).' --abbrev-commit
```

## Packages creation check list:
- [x] Do a fresh clone of the repository
- [x] From the *root* directory, run the release_tools/build.sh (e.g. ```sh release_tools/build.sh development 1.1 beta2```), this will generate the package with the appropriate files

## Complete the release
- [x] Create a new release at github using the announcement previously drafted, and attach the packed files
- [x] ...
- [x] Profit!!!

**Comment by emanuele45** [comment]
Any objection if I pack and ship in no more than a couple of days?
I would love to use the weekend, but I have other problems there and I will not be able to do much...

**Comment by Spuds** [comment]
I don't think we have any additional errors reported to the site (from the last update) ... I have not checked the error log however, we should do that and make sure there is nothing glaring.  Sorry about your weekends being messed up, at least the authorities allow you out during the week 😃

**Comment by emanuele45** [comment]
The log is not exactly clear... actually few random pages of the admin panel were not loading at all. lol

**Comment by Spuds** [comment]
Thats pretty funny, really there are to many admin pages anyway!

Sounds like we need to fix a few things first then ... obviously any more real work needs to go to B4 and just cleanup and fixes for B3 so we can get it out.

**Comment by emanuele45** [comment]
Reminder:
```
wget -O - https://raw.githubusercontent.com/elkarte/Elkarte/development/release_tools/build.sh | sh -s development 1.1 beta3
```

**Comment by emanuele45** [comment]
When #2729 is merged I'll package and release (the command above is wonderfully cool BTW! :stuck_out_tongue: ).

**Comment by Spuds** [comment]
A little automation is always a good thing !

**Comment by emanuele45** [comment]
Gone.
https://github.com/elkarte/Elkarte/releases/tag/v1.1.0-beta.3
