### ISSUE TITLE
Progress tracking issue for 1.1 beta 4 release

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2782]
## Before the release
- [x] Do a fresh clone of the repository
- [x] Verify that index.php, SSI.php, install.php and upgrade.php have the correct CURRENT_VERSION and CACHE_STALE.
- [x] Write a draft of the release announcement. It should consist of:
  - a general description of the release
  - a _release notes_ document including the major changes since the previous version (for development versions like alpha, beta and RC is the previous dev version, for final versions is the previous stable version).
  - a _known issues_ document listing the major issues affecting the release (i.e. bugs not critical enough to be blocker, but potentially annoying)

The following command helps writing the list of changes used in the _release notes_:

```
git log --pretty=format:'[*][bugfix] %s ([url=https://github.com/elkarte/Elkarte/commit/%h]ref[/url]).' --abbrev-commit
```
## Packages creation check list:
- [x] Do a fresh clone of the repository
- [x] From the _root_ directory, run the release_tools/build.sh (e.g. `sh release_tools/build.sh development 1.1 beta2`), this will generate the package with the appropriate files

## Complete the release
- [x] Create a new release at github using the announcement previously drafted, and attach the packed files
- [x] ...
- [x] Profit!!!

**Comment by emanuele45** [comment]
Are we ready?

**Comment by Spuds** [comment]
I know of a few bugs but can drop those in for RC1 ... I'm kind of hoping we do a quick bugs only B4 so we can move onward.

**Comment by emanuele45** [comment]
Okay, tomorrow morning I'll try to update the site and let's give it a couple of days, then I'll pack. :angel:

**Comment by emanuele45** [comment]
The log is mostly empty, just some errors that should not be logged in the first place, but I guess we can figure that out before RC1, so unless there are objections, in 10 hours from now I'll pack and release B4. :smiley_cat:

**Comment by Spuds** [comment]
When I scanned and cleared the log last, I thought the same thing about some of the "clutter" log entries.  Should really be more selective in whats "log" worthy.
